### ISSUE TITLE
fastcgi_param PHP_VALUE 我只在一个站点配置了这个, 为什么其他没有配置的php站点请求也会被捕获了?

### ISSUE THREAD

**Issue by laynefyc** [laynefyc/xhgui-branch#10]
fastcgi_param PHP_VALUE 我只在一个站点配置了这个, 为什么其他没有配置的php站点请求也会被捕获了?

**Comment by laynefyc** [comment]
php-fpm进程会缓存php代码，如果两个站点共用一个php-fpm就会有这种情况。解决办法就是直接在代码的开始执行 
````php
require_once('/Users/markstory/Sites/xhgui/external/header.php');
…………
````

**Comment by mcu-shengwei** [comment]
我也遇到了这个问题,如果在项目里引入header文件，对代码具有侵入性而且增加了风险.如果每个项目配置一个fpm的话部署又很麻烦，感觉这个问题无解了。

**Comment by kingofzihua** [comment]
> 我也遇到了这个问题,如果在项目里引入header文件，对代码具有侵入性而且增加了风险.如果每个项目配置一个fpm的话部署又很麻烦，感觉这个问题无解了。

这个可以解决，配置文件里面有个选项可以控制是否开启，在这里可以处理你的逻辑，比如定义一个数组，里面存放你的域名白名单(你也可以定义ip什么的，主要看你的逻辑)，这样你就可以控制每个请求，
```
'profiler.enable' => function() {
        $domainWhiteList = [
             'xxx',
        ];

        return (int) in_array($_SERVER['SERVER_NAME'],$domainWhiteList);
        //return true;//rand(1, 100) === 42;
    },
```
