### ISSUE TITLE
时间显示的单位变了，但是值还是u秒

### ISSUE THREAD

**Issue by arjing** [laynefyc/xhgui-branch#11]
windows10，PHP 5.6.33 32位
扩展：php_tideways_5.6_x86.dll
![image](https://user-images.githubusercontent.com/10625324/34658456-3a241080-f46a-11e7-9253-207761ad4358.png)

**Comment by seaperson** [comment]
> windows10，PHP 5.6.33 32位
> 扩展：php_tideways_5.6_x86.dll
> ![image](https://user-images.githubusercontent.com/10625324/34658456-3a241080-f46a-11e7-9253-207761ad4358.png)

你好，请问你这个扩展是在哪里下载的？

**Comment by seaperson** [comment]
@arjing 你好，请问你这个php_tideways_5.6_x86.dll扩展是在哪里下载的？
