### ISSUE TITLE
数据为空

### ISSUE THREAD

**Issue by Birjemin** [laynefyc/xhgui-branch#13]
楼主好，我遇到的情况是：xhprof是有数据的，但是xhgui执行时间、CPU时间，内存占用等信息为空，但是请求地址不为空，PHP版本为PHP 7.0.14，xhprof、tideways_xhprof在phpinfo里面都有，请问又遇到过这种情况么？？？

**Comment by Birjemin** [comment]
tideways_xhprof扩展版本5.0.0，xhprof版本是1.1.0

**Comment by laynefyc** [comment]
应该是PHP版本原因，PHP7建议你用tideways扩展。xhprof 扩展不支持PHP7

**Comment by Birjemin** [comment]
已解决，虽然我装的是一个fork版本的xhprof(https://github.com/longxinH/xhprof)，支持php7，但是不支持xhgui调用xhprof(怀疑是不兼容)，改成tideways就好了，不过mongodb的版本如果高于3.5，还会有问题（https://github.com/perftools/xhgui/issues/221），按照这个方法修改一下就好了，感谢楼主的提示！

**Comment by laynefyc** [comment]
可以提个pull request
