### ISSUE TITLE
插入mongo抛出了异常：invalid document for insert: keys cannot contain "."

### ISSUE THREAD

**Issue by seaperson** [laynefyc/xhgui-branch#19]
**BUG描述**
搭建完后可以访问，但一直是初始页面，什么数据都没有，去查错误日志后才发现，在插入mongo的时候抛出了这个异常：
**xhgui - invalid document for insert: keys cannot contain ".": "main()==>load::web/index.php"**
**xhgui - invalid document for insert: keys cannot contain ".": "main()==>load::webroot/index.php"**

系统：ubuntu14.04
php版本：5.6.35
mongo：2.6.12
tidesway：4.1.5

请问这个是什么导致的？大佬有遇到过吗？求教！

**Comment by laynefyc** [comment]
MongoDB 2.6存储数据时Key不能有 . 符号，所以报错了。解决办法如下：
1. 使用MongoDB 2.4

2. 修改代码
打开 xhgui/external/header.php 文件，搜索 ignore_user_abort(true); 函数，在该函数前添加如下代码：
`
        $profile = [];
        foreach($data['profile'] as $key => $value) {
            $profile[strtr($key, ['.' => '_'])] = $value;
        }
        $data['profile'] = $profile;
`

**Comment by seaperson** [comment]
好的 谢谢 我用了类似第二种方法确实解决了，有时间再试试MongoDB2.4，感谢大佬的解答^_^
