### ISSUE TITLE
/url/view? 页面无连接，报错

### ISSUE THREAD

**Issue by lynxcat** [laynefyc/xhgui-branch#21]
**BUG描述**
![image](https://user-images.githubusercontent.com/2222701/40225731-6f854efc-5abc-11e8-80e1-f71a61e6ed80.png)
其余页面都正常，只有这个页面出错。 
PHP版本 PHP 7.1.16 (cli)
MongoDB 版本 v3.6.3

**Comment by laynefyc** [comment]
是bug，我尽快修复

**Comment by laynefyc** [comment]
已经修复

**Comment by lynxcat** [comment]
感谢~
