### ISSUE TITLE
点击详情显示404

### ISSUE THREAD

**Issue by qianqian123** [laynefyc/xhgui-branch#22]
**BUG描述**
php版本7.1.15
可以暂时列表但是点击详情404，

**Comment by laynefyc** [comment]
发一下404页面的URL

**Comment by chaolidd01** [comment]
你好，我也遇到404这个问题，接口请求能记录到，但是查看接口请求详情，每一个都是404.

**Comment by chaolidd01** [comment]
http://tideways.test.work/url/view?url=%2Furl%2Fview%3Furl%3D%252F%253Fdirection%253Dasc%2526sort%253Dtime
这是点击详情后跳转的url

**Comment by chaolidd01** [comment]
404 Page Not Found
The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.

Visit the Home Page
