### ISSUE TITLE
网站添加header.php监控的时候WEB服务报404错误

### ISSUE THREAD

**Issue by sfzhang88** [laynefyc/xhgui-branch#23]
服务器的环境是LNMP,PHP 的版本是5.5.38。
xhgui-branch安装和界面都正常。
服务器上面运行了xhgui-branch和zabbix，在zabbix配置文件里面添加了PHP页面性测试页面并重启了Nginx服务。
location ~ \.php {
            fastcgi_pass   127.0.0.1:9000;
            include        fastcgi_params;
            include        fastcgi.conf;
            fastcgi_param PHP_VALUE "auto_prepend_file=/data/online/xhgui/external/header.php";
        }

PHP性能分析平正常收到监控数据，但我的Zabbix服务页面打开访问的时候报404错误(只有访问/zabbix.php的时候报错，其它PHP页面正常，但这个是入口啊)。

Nginx访问日志：
10.100.82.33 - - [26/Jun/2018:15:31:32 +0800] "GET /zabbix.php?action=dashboard.view HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0" "-" "0.099"
PHP错误日志：
2018/06/26 15:31:32 [error] 25063#0: *3598 open() "/data/online/zabbix/error" failed (2: No such file or directory), client: 10.100.82.33, server: 119.51job.com, request: "GET /zabbix.php?action=dashboard.view HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "test.zmzblog.com"

我把zabbix 配置文件里面的下面行注释之后重启nginx服务，访问Zabbix页面的时候正常。
fastcgi_param PHP_VALUE "auto_prepend_file=/data/online/xhgui/external/header.php";

访问日志：
10.100.82.33 - - [26/Jun/2018:15:56:57 +0800] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0" "-" "0.096"
10.100.82.33 - - [26/Jun/2018:15:56:58 +0800] "GET /zabbix.php?action=dashboard.view HTTP/1.1" 200 4219 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0" "-" "0.330"

请问大概是什么原因导致的，这样上线的话线上服务是否也会打不开，谢谢！

**Comment by laynefyc** [comment]
应该是调用冲突了，auto_prepend_file=/data/online/xhgui/external/header.php  这段代码不一定要放在nginx中。可以在项目入口文件直接 require('/data/online/xhgui/external/header.php') 效果是一样的，能避免冲突。

**Comment by sfzhang88** [comment]
楼主还有什么好的解决方案吗？如何能避免冲突，这样修改了程序的代码，就不是非侵入方式的监控了。
另外把我fastcgi_param PHP_VALUE "auto_prepend_file=/data/online/xhgui/external/header.php"; 加入到xhgui-branch WEB页面配置文件里面，Zabbix页面访问就正常了，xhgui-branch数据采集也正常。
