### ISSUE TITLE
网站添加header.php监控的时候Nginx报502的错误

### ISSUE THREAD

**Issue by sfzhang88** [laynefyc/xhgui-branch#24]
系统环境：Centos 6.8 LNMP PHP 版本 5.5.38
在Nginx 配置文件里面添加header.php的监控的时候网站访问报502错误。

系统日志报下面的错误。请问主要是什么原因造成的，谢谢！

php-fpm[5209]: segfault at 14 ip 00007ff11b35d468 sp 00007ffec05b9d90 error 4 in tideways.so[7ff11b357000+11000]
php-fpm[14502]: segfault at 14 ip 00007f70ba4c0468 sp 00007fff4c357900 error 4 in tideways.so[7f70ba4ba000+11000]
php-fpm[14504]: segfault at 14 ip 00007f70ba4c0468 sp 00007fff4c357900 error 4 in tideways.so[7f70ba4ba000+11000]
php-fpm[36795]: segfault at 14 ip 00007f78f86f6468 sp 00007ffc31a678b0 error 4 in tideways.so[7f78f86f0000+11000]
php-fpm[36797]: segfault at 14 ip 00007f78f86f6468 sp 00007ffc31a678b0 error 4 in tideways.so[7f78f86f0000+11000]
php-fpm[36799]: segfault at 14 ip 00007f78f86f6468 sp 00007ffc31a678b0 error 4 in tideways.so[7f78f86f0000+11000]

**Comment by laynefyc** [comment]
tideways 的版本你是多少? @sfzhang88

**Comment by sfzhang88** [comment]
@laynefyc 麻烦看一下我上面的我问题，能否优化，谢谢！

**Comment by laynefyc** [comment]
@sfzhang88 https://github.com/laynefyc/xhgui-branch/issues/19  之前有人提过了。MongoDB的key不能包含 . 符号造成的。可以通过代码替换。

**Comment by sfzhang88** [comment]
@laynefyc 不懂PHP开发，能否把这个bug fix掉，研究了好长时间没有搞定。
