### ISSUE TITLE
无法查看每个接口的详情，点击详情显示：404 Page Not Found

### ISSUE THREAD

**Issue by chaolidd01** [laynefyc/xhgui-branch#25]
操作系统：ubuntu18.04
php7.2,nginx
mongodb version :3.6.3

接口的cup，执行时间，内存等信息都会被记录，但是点击请求地址下面的接口详情返回
404 Page Not Found
The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.

Visit the Home Page

主页域名：
http://tideways.test01.work/  可以正常访问
http://tideways.test01.work/url/view?url=%2Furl%2Fview%3Furl%3D%252Fwaterfall 报404错误

**Comment by laynefyc** [comment]
@chaolidd01  已知Bug，Composer上没同步更新到，请手动执行更新命令。 

```` 
composer update laynefyc/xhgui-chinese 
````

**Comment by chaolidd01** [comment]
执行上面的语句 
composer update laynefyc/xhgui-chinese 
有问题，提示这个问题
Package "laynefyc/xhgui-chinese" listed for update is not installed. Ignoring.

**Comment by laynefyc** [comment]
@chaolidd01 你不是通过composer安装的吗？你的版本不是最新版本。无论通过哪种方式安装的，代码更新到最新就好了。

**Comment by laynefyc** [comment]
https://github.com/laynefyc/xhgui-branch/blob/master/external/header.php#L178   有问题的代码是这一行，你看看你当前版本的代码是否与最新的一致。

**Comment by chaolidd01** [comment]
我当前版本跟上面那行是一致的。我把
https://github.com/perftools/xhgui
这里的代码也运行了一遍，一样的有这个问题，不知是我哪个配置还有问题吗？

**Comment by chaolidd01** [comment]
虽然这里没找到解决办法，但我后面已经解决了这个问题，感谢楼主的贡献，是我nginx配置的问题
