### ISSUE TITLE
lineGraph是否有问题

### ISSUE THREAD

**Issue by toxmc** [laynefyc/xhgui-branch#26]
**BUG描述**
![image](https://user-images.githubusercontent.com/3990846/43774242-133ed092-9a7b-11e8-94d1-940bb4ff8801.png)
首页直接点击URL 跳转到的页面，图表显示不正常

Mac 
PHP  PHP 7.1.14
xhgui-branch master

**Comment by toxmc** [comment]
每天只取一条展示

**Comment by YangbochenCharles** [comment]
这里感觉应该提供配置uri还是url的功能，url参数都不一样只有一个点了
