### ISSUE TITLE
高版本mongodb 聚合操作 游标选项必填

### ISSUE THREAD

**Issue by wujunwei** [laynefyc/xhgui-branch#30]
当mongodb 版本大于3.5  时会报错  “The 'cursor' option is required, except for aggregate with the explain argument”   ，原因是高版本的mongodb  拓展 的 \MongoCollection::aggregate 方法需传第二个参数

需在 /xhgui-chinese/src/Xhgui/Profiles.php:173  修改。

**Comment by laynefyc** [comment]
https://github.com/garming/xhgui-branch/blob/888b45960f1840fb611ead9c7c9a7057feba6dc0/src/Xhgui/Profiles.php
