### ISSUE TITLE
下载下来之后安装 ，提示这个问题  ，mongodb扩展 1.5.3 php版本7.1.21 mongo 版本3.4.10 tideways_xhprof 版本 5.0.0 

### ISSUE THREAD

**Issue by fanzhengF** [laynefyc/xhgui-branch#31]
bogon:xhgui-branch fanzheng$ /usr/local/Cellar/php@7.1/7.1.21/bin/php install.php 
Downloading composer.
All settings correct for using Composer
Downloading...

Composer (version 1.7.2) successfully installed to: /Users/fanzheng/test1/xhgui2/xhgui-branch/composer.phar
Use it: php composer.phar

Installing dependencies.
ERROR - Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mongodb/mongodb 1.1.2 -> satisfiable by mongodb/mongodb[1.1.2].
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
  Problem 2
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.0.10 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.1.2].
    - Installation request for alcaeus/mongo-php-adapter 1.0.10 -> satisfiable by alcaeus/mongo-php-adapter[1.0.10].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Checking permissions for cache directory.
Attempting to set permissions on cache/
Permissions set on cache/

**Comment by fanzhengF** [comment]
php 版本 7.1.21,tideways_xhprof 扩展已经安装  ，提示Call to undefined function xhprof_enable()  未定义..

**Comment by laynefyc** [comment]
@fanzhengF  php -m 看看 tideways，mongo 扩展是否已经安装，需要重启php-fpm。

**Comment by fanzhengF** [comment]
@laynefyc 昨天搞好了 可以访问了 ，又有个新问题 ，js文件可以执行执行 ，css放到 模板页可以执行，但是用link引用执行不了 。这个问题好奇葩，需要删缓存吗？

**Comment by fanzhengF** [comment]
<img width="1029" alt="2018-10-08 12 53 07" src="https://user-images.githubusercontent.com/29559461/46592905-7ac1f880-caf9-11e8-829e-8aef84eddea2.png">
 css没有加载进来。
