### ISSUE TITLE
sql语句长度超过2000会截断

### ISSUE THREAD

**Issue by seaperson** [laynefyc/xhgui-branch#33]
ubuntu14.04
php5.6.35
tideways4.1.5

你好，请问为什么执行的sql语句存进mongodb的时候最长只有2000个字符？超过2000个字符就直接截断了。有遇到这种情况吗？

**Comment by seaperson** [comment]
打印出tideways_get_spans()这个方法获取到的sql语句已经是截断的了，是扩展问题？

**Comment by laynefyc** [comment]
@seaperson tideways扩展里对字符串做了2000的限制。一般用绑定变量的方式都不会超过2000，数据不会被记录，只记录变量。

**Comment by seaperson** [comment]
好的，谢谢大佬解答！！嗯嗯，确实用的是绑定变量，只不过数据量有点大了。

**Comment by zks888** [comment]
自己修改下php_tideways.h这个文件60行左右的长度的值

#define TIDEWAYS_ANNOTATION_MAX_LENGTH 2000

改为

#define TIDEWAYS_ANNOTATION_MAX_LENGTH 3000
