### ISSUE TITLE
提示：Fatal error: Call to undefined function xhprof_enable() in /var/www/xhgui/external/header.php on line 104

### ISSUE THREAD

**Issue by xingfengsoft** [laynefyc/xhgui-branch#34]
debian 8.7，php5.6，运行时候提示：Fatal error: Call to undefined function xhprof_enable() in /var/www/xhgui/external/header.php on line 104。
检查了php -m，有tideways和mongodb，但是没有xhprof（教程文章中没有提到要安装这个）。不知道遇到这个情况如何处理了，麻烦帮忙

**Comment by xingfengsoft** [comment]
找到问题了，官方的tideways已经不在兼容xhprof，需要去github下载4.x版本的自己做so，不要去官网下载

**Comment by laynefyc** [comment]
@xingfengsoft  你安装了tideways 没装xhprof 出现的 `Call to undefined function xhprof_enable()` 提示？

**Comment by zheteng123** [comment]
请问后来怎么解决的，我安装tideways-php (5.0.36)也报类似的错误，ubuntu16.04
是说也要去tideways下载低版本的扩展自己安装吗？不能用官网git clone方式安装？

**Comment by kbigbus** [comment]
我这边使用的版本是4.1.6。更新了下对应的报错的内容，将xhprof_disable 、 xhprof_enable 改为  tideways_disable 、tideways_enable ，再改了两个常量就可以了。感谢楼主！
php --re tideways 有惊喜
