### ISSUE TITLE
获取不到sql调用详情信息

### ISSUE THREAD

**Issue by chenhua6** [laynefyc/xhgui-branch#35]
您好，请问获取sql调用详情时需要配置什么信息吗？我这边所有接口显示的都是没有sql调用，但实际上是有对数据库进行操作的，使用的php版本7.0.13，mysql版本5.6.36

**Comment by laynefyc** [comment]
@chenhua6  使用tideways扩展才可以。

**Comment by chenhua6** [comment]
> @chenhua6 使用tideways扩展才可以。
必须是tideways扩展吗？tideways_xhprof不可以吗？我安装的是https://github.com/tideways/php-xhprof-extension这个扩展

**Comment by tomlinux** [comment]
安装  https://github.com/tideways/php-xhprof-extension/tree/v4.1.6 报错如下
[root@centos7 php-xhprof-extension]# make
/bin/sh /root/php-xhprof-extension/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1    -I. -I/root/php-xhprof-extension -DPHP_ATOM_INC -I/root/php-xhprof-extension/include -I/root/php-xhprof-extension/main -I/root/php-xhprof-extension -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-xhprof-extension/tideways_xhprof.c -o tideways_xhprof.lo
mkdir .libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/php-xhprof-extension -DPHP_ATOM_INC -I/root/php-xhprof-extension/include -I/root/php-xhprof-extension/main -I/root/php-xhprof-extension -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-xhprof-extension/tideways_xhprof.c  -fPIC -DPIC -o .libs/tideways_xhprof.o
In file included from /root/php-xhprof-extension/tideways_xhprof.c:9:0:
/root/php-xhprof-extension/php_tideways_xhprof.h:33:5: 错误：未知的类型名‘zend_string’
     zend_string *parent_class;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:34:5: 错误：未知的类型名‘zend_string’
     zend_string *parent_function;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:36:5: 错误：未知的类型名‘zend_string’
     zend_string *child_class;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:37:5: 错误：未知的类型名‘zend_string’
     zend_string *child_function;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:40:5: 错误：未知的类型名‘zend_long’
     zend_long count;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:41:5: 错误：未知的类型名‘zend_long’
     zend_long wall_time;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:42:5: 错误：未知的类型名‘zend_long’
     zend_long cpu_time;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:43:5: 错误：未知的类型名‘zend_long’
     zend_long memory;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:44:5: 错误：未知的类型名‘zend_long’
     zend_long memory_peak;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:56:5: 错误：未知的类型名‘zend_string’
     zend_string         *function_name;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:57:5: 错误：未知的类型名‘zend_string’
     zend_string         *class_name;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:75:5: 错误：未知的类型名‘zend_string’
     zend_string *root;
     ^
/root/php-xhprof-extension/php_tideways_xhprof.h:80:5: 错误：未知的类型名‘zend_long’
     zend_long flags;
     ^
In file included from /root/php-xhprof-extension/tideways_xhprof.c:13:0:
/root/php-xhprof-extension/tracing.h:17:146: 错误：未知的类型名‘zend_long’
 xhprof_callgraph_bucket *tracing_callgraph_bucket_find(xhprof_callgraph_bucket *bucket, xhprof_frame_t *current_frame, xhprof_frame_t *previous, zend_long key);
                                                                                                                                                  ^
/root/php-xhprof-extension/tracing.h:19:20: 错误：未知的类型名‘zend_long’
 void tracing_begin(zend_long flags TSRMLS_DC);
                    ^
/root/php-xhprof-extension/tracing.h: 在函数‘tracing_fast_free_frame’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tracing.h:43:25: 附注：in expansion of macro ‘TXRG’
     p->previous_frame = TXRG(frame_free_list);
                         ^
/root/php-xhprof-extension/tracing.h:26:46: 附注：每个未声明的标识符在其出现的函数内只报告一次
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tracing.h:43:25: 附注：in expansion of macro ‘TXRG’
     p->previous_frame = TXRG(frame_free_list);
                         ^
/root/php-xhprof-extension/tracing.h:43:30: 错误：‘frame_free_list’未声明(在此函数内第一次使用)
     p->previous_frame = TXRG(frame_free_list);
                              ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h: 在函数‘tracing_fast_alloc_frame’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tracing.h:51:9: 附注：in expansion of macro ‘TXRG’
     p = TXRG(frame_free_list);
         ^
/root/php-xhprof-extension/tracing.h:51:14: 错误：‘frame_free_list’未声明(在此函数内第一次使用)
     p = TXRG(frame_free_list);
              ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h: 在文件作用域：
/root/php-xhprof-extension/tracing.h:61:1: 错误：未知的类型名‘zend_string’
 static zend_always_inline zend_string* tracing_get_class_name(zend_execute_data *data TSRMLS_DC)
 ^
/root/php-xhprof-extension/tracing.h: 在函数‘tracing_get_class_name’中:
/root/php-xhprof-extension/tracing.h:69:21: 错误：‘zend_execute_data’没有名为‘func’的成员
     curr_func = data->func;
                     ^
/root/php-xhprof-extension/tracing.h:74:9: 警告：返回了不兼容的指针类型 [默认启用]
         return curr_func->common.scope->name;
         ^
/root/php-xhprof-extension/tracing.h: 在文件作用域：
/root/php-xhprof-extension/tracing.h:80:1: 错误：未知的类型名‘zend_string’
 static zend_always_inline zend_string* tracing_get_function_name(zend_execute_data *data TSRMLS_DC)
 ^
/root/php-xhprof-extension/tracing.h: 在函数‘tracing_get_function_name’中:
/root/php-xhprof-extension/tracing.h:88:21: 错误：‘zend_execute_data’没有名为‘func’的成员
     curr_func = data->func;
                     ^
/root/php-xhprof-extension/tracing.h:99:5: 警告：返回了不兼容的指针类型 [默认启用]
     return curr_func->common.function_name;
     ^
/root/php-xhprof-extension/tracing.h: 在文件作用域：
/root/php-xhprof-extension/tracing.h:102:61: 错误：未知的类型名‘zend_string’
 zend_always_inline static int tracing_enter_frame_callgraph(zend_string *root_symbol, zend_execute_data *execute_data TSRMLS_DC)
                                                             ^
/root/php-xhprof-extension/tracing.h: 在函数‘tracing_exit_frame_callgraph’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tracing.h:162:37: 附注：in expansion of macro ‘TXRG’
     xhprof_frame_t *current_frame = TXRG(callgraph_frames);
                                     ^
/root/php-xhprof-extension/tracing.h:162:42: 错误：‘callgraph_frames’未声明(在此函数内第一次使用)
     xhprof_frame_t *current_frame = TXRG(callgraph_frames);
                                          ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:164:5: 错误：未知的类型名‘zend_long’
     zend_long duration = time_milliseconds(TXRG(clock_source), TXRG(timebase_factor)) - current_frame->wt_start;
     ^
/root/php-xhprof-extension/tracing.h:164:49: 错误：‘clock_source’未声明(在此函数内第一次使用)
     zend_long duration = time_milliseconds(TXRG(clock_source), TXRG(timebase_factor)) - current_frame->wt_start;
                                                 ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:164:69: 错误：‘timebase_factor’未声明(在此函数内第一次使用)
     zend_long duration = time_milliseconds(TXRG(clock_source), TXRG(timebase_factor)) - current_frame->wt_start;
                                                                     ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:168:44: 错误：‘callgraph_buckets’未声明(在此函数内第一次使用)
     xhprof_callgraph_bucket *bucket = TXRG(callgraph_buckets)[slot];
                                            ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:170:12: 警告：赋值时将整数赋给指针，未作类型转换 [默认启用]
     bucket = tracing_callgraph_bucket_find(bucket, current_frame, previous, key);
            ^
/root/php-xhprof-extension/tracing.h:175:103: 警告：条件表达式中指针/整数类型不匹配 [默认启用]
         bucket->child_class = current_frame->class_name ? zend_string_copy(current_frame->class_name) : NULL;
                                                                                                       ^
/root/php-xhprof-extension/tracing.h:176:32: 警告：赋值时将整数赋给指针，未作类型转换 [默认启用]
         bucket->child_function = zend_string_copy(current_frame->function_name);
                                ^
/root/php-xhprof-extension/tracing.h:179:119: 警告：条件表达式中指针/整数类型不匹配 [默认启用]
             bucket->parent_class = previous->class_name ? zend_string_copy(current_frame->previous_frame->class_name) : NULL;
                                                                                                                       ^
/root/php-xhprof-extension/tracing.h:180:37: 警告：赋值时将整数赋给指针，未作类型转换 [默认启用]
             bucket->parent_function = zend_string_copy(previous->function_name);
                                     ^
/root/php-xhprof-extension/tracing.h:205:31: 错误：‘num_alloc’未声明(在此函数内第一次使用)
     bucket->num_alloc += TXRG(num_alloc) - current_frame->num_alloc;
                               ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:206:30: 错误：‘num_free’未声明(在此函数内第一次使用)
     bucket->num_free += TXRG(num_free) - current_frame->num_free;
                              ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:207:34: 错误：‘amount_alloc’未声明(在此函数内第一次使用)
     bucket->amount_alloc += TXRG(amount_alloc) - current_frame->amount_alloc;
                                  ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:209:14: 错误：‘flags’未声明(在此函数内第一次使用)
     if (TXRG(flags) & TIDEWAYS_XHPROF_FLAGS_CPU) {
              ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tracing.h:221:10: 错误：‘function_hash_counters’未声明(在此函数内第一次使用)
     TXRG(function_hash_counters)[current_frame->hash_code]--;
          ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c: 在函数‘zif_tideways_xhprof_enable’中:
/root/php-xhprof-extension/tideways_xhprof.c:26:5: 错误：未知的类型名‘zend_long’
     zend_long flags = 0;
     ^
/root/php-xhprof-extension/tideways_xhprof.c: 在函数‘zm_startup_tideways_xhprof’中:
/root/php-xhprof-extension/tideways_xhprof.c:67:28: 警告：从不兼容的指针类型赋值 [默认启用]
     _zend_execute_internal = zend_execute_internal;
                            ^
/root/php-xhprof-extension/tideways_xhprof.c:68:27: 警告：从不兼容的指针类型赋值 [默认启用]
     zend_execute_internal = tideways_xhprof_execute_internal;
                           ^
In file included from /root/php-xhprof-extension/tideways_xhprof.c:13:0:
/root/php-xhprof-extension/tideways_xhprof.c: 在函数‘zm_deactivate_tideways_xhprof’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tideways_xhprof.c:97:18: 附注：in expansion of macro ‘TXRG’
         bucket = TXRG(callgraph_buckets)[i];
                  ^
/root/php-xhprof-extension/tideways_xhprof.c:97:23: 错误：‘callgraph_buckets’未声明(在此函数内第一次使用)
         bucket = TXRG(callgraph_buckets)[i];
                       ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c: 在函数‘zm_info_tideways_xhprof’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tideways_xhprof.c:121:13: 附注：in expansion of macro ‘TXRG’
     switch (TXRG(clock_source)) {
             ^
/root/php-xhprof-extension/tideways_xhprof.c:121:18: 错误：‘clock_source’未声明(在此函数内第一次使用)
     switch (TXRG(clock_source)) {
                  ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c: 在函数‘tideways_xhprof_execute_internal’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tideways_xhprof.c:167:10: 附注：in expansion of macro ‘TXRG’
     if (!TXRG(enabled) || (TXRG(flags) & TIDEWAYS_XHPROF_FLAGS_NO_BUILTINS) > 0) {
          ^
/root/php-xhprof-extension/tideways_xhprof.c:167:15: 错误：‘enabled’未声明(在此函数内第一次使用)
     if (!TXRG(enabled) || (TXRG(flags) & TIDEWAYS_XHPROF_FLAGS_NO_BUILTINS) > 0) {
               ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c:167:33: 错误：‘flags’未声明(在此函数内第一次使用)
     if (!TXRG(enabled) || (TXRG(flags) & TIDEWAYS_XHPROF_FLAGS_NO_BUILTINS) > 0) {
                                 ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c:168:9: 警告：传递‘execute_internal’的第 2 个参数时在不兼容的指针类型间转换 [默认启用]
         execute_internal(execute_data, return_value TSRMLS_CC);
         ^
In file included from /usr/local/php/include/php/Zend/zend_API.h:30:0,
                 from /usr/local/php/include/php/main/php.h:39,
                 from /root/php-xhprof-extension/tideways_xhprof.c:5:
/usr/local/php/include/php/Zend/zend_execute.h:62:15: 附注：需要类型‘struct _zend_fcall_info *’，但实参的类型为‘struct zval *’
 ZEND_API void execute_internal(zend_execute_data *execute_data_ptr, struct _zend_fcall_info *fci, int return_value_used TSRMLS_DC);
               ^
/root/php-xhprof-extension/tideways_xhprof.c:168:9: 错误：提供给函数‘execute_internal’的实参太少
         execute_internal(execute_data, return_value TSRMLS_CC);
         ^
In file included from /usr/local/php/include/php/Zend/zend_API.h:30:0,
                 from /usr/local/php/include/php/main/php.h:39,
                 from /root/php-xhprof-extension/tideways_xhprof.c:5:
/usr/local/php/include/php/Zend/zend_execute.h:62:15: 附注：在此声明
 ZEND_API void execute_internal(zend_execute_data *execute_data_ptr, struct _zend_fcall_info *fci, int return_value_used TSRMLS_DC);
               ^
/root/php-xhprof-extension/tideways_xhprof.c:175:9: 警告：传递‘execute_internal’的第 2 个参数时在不兼容的指针类型间转换 [默认启用]
         execute_internal(execute_data, return_value TSRMLS_CC);
         ^
In file included from /usr/local/php/include/php/Zend/zend_API.h:30:0,
                 from /usr/local/php/include/php/main/php.h:39,
                 from /root/php-xhprof-extension/tideways_xhprof.c:5:
/usr/local/php/include/php/Zend/zend_execute.h:62:15: 附注：需要类型‘struct _zend_fcall_info *’，但实参的类型为‘struct zval *’
 ZEND_API void execute_internal(zend_execute_data *execute_data_ptr, struct _zend_fcall_info *fci, int return_value_used TSRMLS_DC);
               ^
/root/php-xhprof-extension/tideways_xhprof.c:175:9: 错误：提供给函数‘execute_internal’的实参太少
         execute_internal(execute_data, return_value TSRMLS_CC);
         ^
In file included from /usr/local/php/include/php/Zend/zend_API.h:30:0,
                 from /usr/local/php/include/php/main/php.h:39,
                 from /root/php-xhprof-extension/tideways_xhprof.c:5:
/usr/local/php/include/php/Zend/zend_execute.h:62:15: 附注：在此声明
 ZEND_API void execute_internal(zend_execute_data *execute_data_ptr, struct _zend_fcall_info *fci, int return_value_used TSRMLS_DC);
               ^
In file included from /root/php-xhprof-extension/tideways_xhprof.c:13:0:
/root/php-xhprof-extension/tideways_xhprof.c:180:35: 错误：‘callgraph_frames’未声明(在此函数内第一次使用)
     if (is_profiling == 1 && TXRG(callgraph_frames)) {
                                   ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c: 在函数‘tideways_xhprof_execute_ex’中:
/root/php-xhprof-extension/tracing.h:26:46: 错误：‘tideways_xhprof’未声明(在此函数内第一次使用)
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                              ^
/root/php-xhprof-extension/tideways_xhprof.c:189:10: 附注：in expansion of macro ‘TXRG’
     if (!TXRG(enabled)) {
          ^
/root/php-xhprof-extension/tideways_xhprof.c:189:15: 错误：‘enabled’未声明(在此函数内第一次使用)
     if (!TXRG(enabled)) {
               ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
/root/php-xhprof-extension/tideways_xhprof.c:198:35: 错误：‘callgraph_frames’未声明(在此函数内第一次使用)
     if (is_profiling == 1 && TXRG(callgraph_frames)) {
                                   ^
/root/php-xhprof-extension/tracing.h:26:63: 附注：in definition of macro ‘TXRG’
 #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)
                                                               ^
make: *** [tideways_xhprof.lo] 错误 1

**Comment by chenhua6** [comment]
> @chenhua6 https://github.com/tideways/php-xhprof-extension/tree/v4.1.6 安装这个版本，新版本去除了SPANS函数

安装这个版本的扩展失败了 
![image](https://user-images.githubusercontent.com/13075788/48821114-e94dd380-ed92-11e8-877d-2449664b6ac6.png)

**Comment by laynefyc** [comment]
执行phpize 到 ./configure --with-php-config 的命令都发出来看看

**Comment by kbigbus** [comment]
PHP版本：7.0.13

**Comment by laynefyc** [comment]
https://github.com/laynefyc/xhgui-branch/blob/ad6e0c0a3eaf9b5b0438cd4a3d3db937f1954058/config/config.default.php#L12  只改这里就行

**Comment by deathkel** [comment]
> tideways版本：4.1.6 需要调整header.php 的文件 把相关代码都调整成扩展为tideways的流程即可！

请问能给个例子吗，我这边也是跟题主一样没有收集到sql

**Comment by kbigbus** [comment]
@deathkel  按照 @laynefyc 贴的方法就能解决了

**Comment by purewater2011** [comment]
如果4.1.6装不上，可以试试4.1.7
macos10.15，php7.3.12。可以收集到sql了

**Comment by caiyi3857200** [comment]
我现在也蒙圈了, 用的框架是公司魔改之后的,然后SQL这边没看到任何采集信息, 不确定是自己配置问题还是魔改之后的问题

**Comment by caiyi3857200** [comment]
php 7.1.18
tideways_xhprof : 5.0.0
mongodb : 1.4.4
![image](https://user-images.githubusercontent.com/40154970/236150522-a70ad2d4-9971-4498-8a66-49dc3351e554.png)

![image](https://user-images.githubusercontent.com/40154970/236150622-6dbd1205-3ad2-446c-b2bb-8da15cac9d09.png)
