### ISSUE TITLE
Class 'MongoClient' not found 

### ISSUE THREAD

**Issue by lu8533783** [laynefyc/xhgui-branch#36]
操作系统： centos7.4
PHP版本： 7.5
扩展版本 ：
MongoDB extension version | 1.5.3
MongoDb版本：3.6.3

访问提示
Fatal error: Uncaught Error: Class 'MongoClient' not found in /www/wwwroot/xhgui/src/Xhgui/ServiceContainer.php:77

**Comment by laynefyc** [comment]
php -m 看看有没有mongo扩展，需要重启php-fpm。

**Comment by lu8533783** [comment]
有拓展的

**Comment by lu8533783** [comment]
php版本：7.2 （上面错了）
![image](https://user-images.githubusercontent.com/11518287/48708895-d1fdd180-ec3e-11e8-9495-b60621ac267f.png)
7.2没这个包

**Comment by lu8533783** [comment]
网上的大多数php版本的5.X的，对于5.X来说需要的扩展文件是mongo.so文件，对应的下载链接：https://pecl.php.net/package/mongo

都是比较老的版本，对于7.X版本需要生成的扩展文件是mongodb.so文件.
是不是7不支持mongo了改为mongodb

**Comment by lu8533783** [comment]
为什么换成file 也不行

**Comment by lu8533783** [comment]
预计啥时候能升级？

**Comment by lu8533783** [comment]
原版对比https://github.com/perftools/xhgui/blob/master/config/config.default.php
这个文件不一致。我安装原版可以使用

**Comment by laynefyc** [comment]
原版也是调用 MongoClient 类初始化。如果是mongo扩展问题的话，都会报这个错。说明不是mongo扩展的问题，你再排查下有没有其他错误信息。

**Comment by lu8533783** [comment]
我降成php5.6了，所以MongoClient 正常使用了。 
但是你这个版本https://github.com/perftools/xhgui/blob/master/external/header.php这个文件不一致。我用原版的可以运行

**Comment by laynefyc** [comment]
你安装的扩展应该是   tideways_xhprof    https://github.com/laynefyc/xhgui-branch/blob/ad6e0c0a3eaf9b5b0438cd4a3d3db937f1954058/config/config.default.php#L12  这里修改就好了。

**Comment by emund1101** [comment]
我也出现一样的问题哦，php7不支持 mongo的库，等待更新。
