### ISSUE TITLE
php-xhprof-extension 和 php-profiler-extension 这俩扩展有什么区别

### ISSUE THREAD

**Issue by zheteng123** [laynefyc/xhgui-branch#38]
php-xhprof-extension 和 php-profiler-extension 这俩扩展有什么区别  麻烦大佬能科普下吗

**Comment by laynefyc** [comment]
最早是facebook出了一款 xhprof 扩展，用来给PHP程序本地调优。后来facebook全线转到了HHVM，这个扩展也就被搁置。有几位PHPer基于 xhprof 开发了 php-profiler-extension，uprofiler等扩展，并进行维护。后来tideways公司发现可以提供2B的商业监控服务，于是基于php-profiler-extension开发了 php-xhprof-extension，并长期更新维护，第一个支持了PHP7。 所以建议使用  https://github.com/tideways/php-xhprof-extension/tree/v4.1.6    版本

**Comment by zheteng123** [comment]
多谢大佬科普~

**Comment by laynefyc** [comment]
'extension' => 'tideways',

**Comment by zheteng123** [comment]
改成了'extension' => 'tideways',
但还是有以下问题：
1.图表中还是没有sql数据，也没有CPU和内存图，只有CPU和内存的数据
2.使用xhgui-branch项目时，调用链路加载不出来，原版的xhgui很快能加载出来

**Comment by zheteng123** [comment]
改成了'extension' => 'tideways',
但还是有以下问题：
1.图表中还是没有sql数据，也没有CPU和内存图，只有CPU和内存的数据
2.使用xhgui-branch项目时，调用链路加载不出来，原版的xhgui很快能加载出来

**Comment by laynefyc** [comment]
请提供详细的报错信息，和SQL调用语句。
