### ISSUE TITLE
Call to undefined function tideways_enable()

### ISSUE THREAD

**Issue by secretgao** [laynefyc/xhgui-branch#39]
**版本信息:**
 - 操作系统: [e.g. CentOS 7]
 - PHP [e.g. PHP7.2]
 - 扩展 [e.g. tideway.so 7.2]
 - MongodDB 版本 [e.g. MongodDB v4.0.4]

当我把项目里的config。php  rand(1, 100) === 42 换成 true 的时候 
 // Profile 1 in 100 requests.
    // You can return true to profile every request.
    'profiler.enable' => function() {
        return true; //rand(1, 100) === 42;
    },
**具体报错信息：**
`
[Fatal error: Uncaught Error: Call to undefined function tideways_enable() in /usr/local/nginx/html/xhgui/vendor/perftools/xhgui-collector/external/header.php:99 Stack trace: #0 /usr/local/nginx/html/xhgui/external/header.php(9): require_once() #1 {main} thrown in /usr/local/nginx/html/xhgui/vendor/perftools/xhgui-collector/external/header.php on line 99`

**Comment by laynefyc** [comment]
项目的说明文件（README文件）中有详细说明。
