### ISSUE TITLE
安装好了有几个问题

### ISSUE THREAD

**Issue by Longjianghu** [laynefyc/xhgui-branch#4]
1、web界面不支持多站点
2、没有权限控制，连基本的用户名密码校验都没有
3、在哪里可以查看SQL执行时间，如果有就更好了，目前没有找到。

**Comment by laynefyc** [comment]
1. web界面不支持多站点
你说的是域名没显示吗？域名在SERVER中有记录，前端没做条件筛选。这个是个好的优化点。
2. 没有权限控制，连基本的用户名密码校验都没有
权限控制暂时不会考虑，UI的代码建议部署在本地，前端界面完全分离也是我打算做的。
3. 在哪里可以查看SQL执行时间，如果有就更好了，目前没有找到。
任何页面的 日期链接 都会跳到函数执行的时间，包含sql执行时间。

**Comment by Longjianghu** [comment]
1、域名在SERVER有记录我在数据库里可以查看但是界面上也需要显示,这样也便于筛选。
2、在实际的运用过程中还是需要简单的密码控制，不可能让人打开之后就可以查看统计信息。
3、表达有误，我实际上问的是能不能查看具体SQL语句的执行时间，最好是能显示出SQL，便于性能优化。
4、汉化不完整
5、函数或者方法监控能不不统计PHP本身的函数？

**Comment by liuhui5354** [comment]
执行时间和CPU时间都是
-2147483.6 ms
是不是哪里配置错了？
timezone没问题

**Comment by laynefyc** [comment]
@liuhui5354 你是不是Windows服务器？这是扩展没有拿到数据，tideways和xhprof并不支持所有操作系统。你可以看看MongoDB里面的原始数据。
具体语法如下：
> mongo
> use xhprof
> db.results.find().limit(10)

重点查看wt参数的值。
