### ISSUE TITLE
PHP7 关于 mongodb 的支持

### ISSUE THREAD

**Issue by woowli** [laynefyc/xhgui-branch#40]
**版本信息:**
 - 操作系统: [CentOS 7]
 - PHP [PHP7.0.30]
 - 扩展 [tideway.so ]
 - MongoDB extension version  [1.5.3]
 - MongodDB 版本  [v1.4.2]

**具体报错信息：**
Fatal error: Uncaught Error: Class 'MongoClient' not found in /home/yuli/work/img-server/vendor/laynefyc/xhgui-chinese/src/Xhgui/ServiceContainer.php:77 Stack trace: #0 /home/yuli/work/img-server/vendor/pimple/pimple/lib/Pimple.php(126): Xhgui_ServiceContainer->{closure}(Object(Xhgui_ServiceContainer)) #1 /home/yuli/work/img-server/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Xhgui_ServiceContainer)) #2 /home/yuli/work/img-server/vendor/laynefyc/xhgui-chinese/src/Xhgui/ServiceContainer.php(87): Pimple->offsetGet('db') #3 /home/yuli/work/img-server/vendor/pimple/pimple/lib/Pimple.php(83): Xhgui_ServiceContainer->{closure}(Object(Xhgui_ServiceContainer)) #4 /home/yuli/work/img-server/vendor/laynefyc/xhgui-chinese/src/Xhgui/ServiceContainer.php(124): Pimple->offsetGet('profiles') #5 /home/yuli/work/img-server/vendor/pimple/pimple/lib/Pimple.php(83): Xhgui_ServiceContainer->{closure}(Object(Xhgui_ServiceContainer)) #6 /home/yuli/work/img-server/vendor/laynefyc/xhgui-chinese/src/routes.php(104): Pimple->of in /home/yuli/work/img-server/vendor/laynefyc/xhgui-chinese/src/Xhgui/ServiceContainer.php on line 77

在这个问题提出来之前，我有仔细看了一个相关的 [issue](https://github.com/laynefyc/xhgui-branch/issues/36) ，但我没能从中找到解决问题的答案。
关于mongodb有一些不解：源码中使用的是 $mongo = new MongoClient($config['db.host'], $config['db.options']);  但实际上 php7 使用的 mongodb 扩展已经不支持这种方式了。可为什么看一些楼主，基于 php7 有安装成功了的？ 请问这个是不是要等到下一版的更新才能支持 php7？

**Comment by laynefyc** [comment]
官方是说 this class is deprecated。你这个报错可能是因为tideway.so版本的原因。V5版本叫tideways_xhprof  ，配置文件改一下https://github.com/laynefyc/xhgui-branch/blob/ad6e0c0a3eaf9b5b0438cd4a3d3db937f1954058/config/config.default.php#L12     如果不知道版本php -m 也能查看完整的名字。php --re  tideway 查看扩展版本

**Comment by laynefyc** [comment]
@woowli    源码中使用的是 $mongo = new MongoClient($config['db.host'], $config['db.options']); 但实际上 php7 使用的 mongodb 扩展已经不支持这种方式了。   

官方： This extension that defines this class is deprecated.    官方只是不建议使用，MongoClient函数无论是mongo.so还是mongodb.so 都支持。

**Comment by wtry** [comment]
7.3.1 也有同样的问题，我试着改称用file也不行

**Comment by wtry** [comment]
php中MongoDB和Mongo是不一样的扩展，两者不兼容，MongoDate在新版扩展中没有了

**Comment by woowli** [comment]
嗯嗯，已经解决了。是 tideways 的原因，php7 版本需要安装 tideways_xhprof。谢谢：)

**Comment by zzpwestlife** [comment]
安装了 tideways_xhprof， 问题依旧，等待跟进

**Comment by mowangjuanzi** [comment]
我 直接安装的官方原版的就好了。

你们这么可以玩。 直接使用官方原版就可以用了。不过就是语言是英文的。

**Comment by laynefyc** [comment]
官方原版只是改了config里面的扩展名，tideways改名了，首页有说明。
