### ISSUE TITLE
前端页面没法显示日期选择框, console 提示 datepicker is not a function

### ISSUE THREAD

**Issue by huangliulin** [laynefyc/xhgui-branch#42]
![image](https://user-images.githubusercontent.com/13099862/53218050-920f1600-3695-11e9-8d3c-886df20b9a6a.png)

**Comment by laynefyc** [comment]
@huangliulin  URL发来看看，还有浏览器版本。

**Comment by huangliulin** [comment]
@laynefyc 首页 就会出现 http://localhost:83/index.php
Google Chrome 最新版：版本 72.0.3626.119（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/13099862/53279362-b7119080-374a-11e9-9ea7-42237aec8e6b.png)
用Edge和IE11是正常的
