### ISSUE TITLE
MongoDB Authentication failed.

### ISSUE THREAD

**Issue by cnjackven** [laynefyc/xhgui-branch#43]
**版本信息:**
 - 操作系统: CentOS 7
 - PHP: PHP7.2.15
 - 扩展 : tideways_xhprof.so
 - MongodDB 版本:  MongodDB v4.0.6

问题一：配置文件中增加了mongod的账户密码，一直提示这个： Authentication failed.
去掉mongod的验证就恢复正常，很奇怪
配置如：
`    'db.options' => array('connect' => true, "username"=>"xhprof","password"=>"xhprof"),
`
问题二：在虚拟主机中增加了：
`  fastcgi_param PHP_VALUE "auto_prepend_file=/webdata/ser/xhgui/external/external/header.php";
`
但是没有任何信息记录，只有require_once('/webdata/ser/xhgui/external/header.php'); 加载才有

**具体报错信息：**
`Aw shoot, Xhgui hit an error
Authentication failed.

You should check the following things:

Ensure that Mongo has been started
That config/config.php has the right connection information.
That the cache/ directory has the correct permissions.
Stack trace
#0 /webdata/ser/xhgui/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(563): Alcaeus\MongoDbAdapter\ExceptionConverter::toLegacy(Object(MongoDB\Driver\Exception\AuthenticationException))
#1 /webdata/ser/xhgui/src/Xhgui/ServiceContainer.php(78): MongoCollection->findOne()
#2 /webdata/ser/xhgui/vendor/pimple/pimple/lib/Pimple.php(126): Xhgui_ServiceContainer->{closure}(Object(Xhgui_ServiceContainer))
#3 /webdata/ser/xhgui/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Xhgui_ServiceContainer))
#4 /webdata/ser/xhgui/src/Xhgui/ServiceContainer.php(88): Pimple->offsetGet('db')
#5 /webdata/ser/xhgui/vendor/pimple/pimple/lib/Pimple.php(83): Xhgui_ServiceContainer->{closure}(Object(Xhgui_ServiceContainer))
#6 /webdata/ser/xhgui/src/Xhgui/ServiceContainer.php(117): Pimple->offsetGet('profiles')
#7 /webdata/ser/xhgui/vendor/pimple/pimple/lib/Pimple.php(83): Xhgui_ServiceContainer->{closure}(Object(Xhgui_ServiceContainer))
#8 /webdata/ser/xhgui/src/routes.php(24): Pimple->offsetGet('runController')
#9 [internal function]: {closure}()
#10 /webdata/ser/xhgui/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#11 /webdata/ser/xhgui/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#12 /webdata/ser/xhgui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#13 /webdata/ser/xhgui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#14 /webdata/ser/xhgui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#15 /webdata/ser/xhgui/src/Xhgui/Middleware/Render.php(11): Slim\Middleware\SessionCookie->call()
#16 /webdata/ser/xhgui/vendor/slim/slim/Slim/Slim.php(1300): Xhgui_Middleware_Render->call()
#17 /webdata/ser/xhgui/webroot/index.php(10): Slim\Slim->run()
#18 {main}
`

**Comment by laynefyc** [comment]
在MongoDB中设置了帐号密码后，直接在服务器上能登录吗？ 先试试服务器上mongo客户端能不能登录，再试试PHP登录。 auto_prepend_file 生效要重启php-fpm，重启后还不生效的话在header.php第一行打个log看能不能成功

**Comment by cnjackven** [comment]
MongoDB设置了账号在服务器和本机电脑上都能连接进入mongoDB数据库。在服务器上使用mongo命令登录也没问题。看我的配置有问题吗？应该没问题吧。
header.php这个问题已经解决了，换一个位置就好了。
另外请教一下，能对请求的信息进行分区吗？比如一台服务器上运行了多个虚拟主机的情况下，能区分查看一个虚拟主机下的所有请求记录吗？

**Comment by cnjackven** [comment]
MongoDB账户验证数据库的问题，已解决了，账户只能在admin库，不能在xhprof库。这个不能设置使用哪个数据库做验证吗？

同一个服务器多个虚拟主机，在xhgui里怎么能快速的分开哪个是哪个网站的捏？

**Comment by laynefyc** [comment]
暂时不支持网站区分，新版本已经在开发中了

**Comment by jian-D** [comment]
> MongoDB账户验证数据库的问题，已解决了，账户只能在admin库，不能在xhprof库。这个不能设置使用哪个数据库做验证吗？
> 
> 同一个服务器多个虚拟主机，在xhgui里怎么能快速的分开哪个是哪个网站的捏？

我也遇到这个问题，但是我们服务器mongoDb 必须在新库验证，这个怎么搞，请问你后面有解决这个问题吗？
