### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Xhgui_Config' not found

### ISSUE THREAD

**Issue by Artgerry** [laynefyc/xhgui-branch#45]
**版本信息:**
 - 操作系统: [macOS Mojave 10.14.3]
 - PHP [PHP 7.1.1]
 - 扩展 [tideways v4.1.5]
 - MongodDB 版本 [MongodDB v4.0.9]

**PHP信息:**
![image](https://user-images.githubusercontent.com/20944512/57205493-9e96df80-6ff1-11e9-8f79-1854e684d82e.png)
访问header.php报错信息：
![image](https://user-images.githubusercontent.com/20944512/57205539-e158b780-6ff1-11e9-8bce-1ca1741826fe.png)

**具体报错信息：**
![image](https://user-images.githubusercontent.com/20944512/57205551-f59cb480-6ff1-11e9-835a-745b56123ac5.png)

**Comment by lics1216** [comment]
"PHP message: PHP Fatal error:  Uncaught Error: Class 'Xhgui_Config' not found in /data/tmp/xhgui-branch/src/bootstrap.php:13
