### ISSUE TITLE
获取不到sql详情

### ISSUE THREAD

**Issue by ice-leng** [laynefyc/xhgui-branch#46]
**版本信息:**
 - 操作系统: mac
 - PHP  7.1.20
 - 扩展  xhprof
 - MongodDB v4.0.0

**具体报错信息：**
使用什么扩展能有sql详情
https://github.com/tideways/php-xhprof-extension/tree/v4.1.6 
这个版本支持7.1吗？

**Comment by laynefyc** [comment]
https://tideways.com/profiler/downloads  到这里下载试试

**Comment by flybeta1988** [comment]
> https://tideways.com/profiler/downloads 到这里下载试试

为什么最新版的不支持收集sql执行详情？而只在 v4.1.x支持呢？

**Comment by lz71** [comment]
环境信息：
php信息：
PHP 7.2.16 (cli) (built: Jun 13 2020 18:01:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
扩展信息：
tideways5.0.2 ，从https://github.com/tideways/php-xhprof-extension/releases下载
MongoDB信息：
MongoDB shell version v4.2.8
问题：
所有请求接口的SQL执行详情都是没有SQL调用
备注：
php换为以下版本，其余工具版本如上所示不变，也是相同的问题
PHP 7.3.11 (cli) (built: Mar 23 2020 14:31:12) ( NTS )

**Comment by laynefyc** [comment]
Try install tideways v4.1.7
