### ISSUE TITLE
一直无法获取数据

### ISSUE THREAD

**Issue by iawyvergw** [laynefyc/xhgui-branch#50]
**一定要读**
在提交BUG之前请查阅README文件，常见的安装与配置问题都有对应解决办法 。再查看历史ISSUE https://github.com/laynefyc/xhgui-branch/issues?utf8=%E2%9C%93&q=is%3Aissue 是否有答案。都解决不了，请认真填写如下信息

**版本信息:**
 - 操作系统: CentOS_7_03_64
 - PHP PHP 5.6.9
 - 扩展  tideway 5.0.48
 - MongodDB 版本 1.5.2

**PHP信息:**
1. 运行php -m 将结果粘贴到当前文本中
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
ereg
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mongo
mongodb
mssql
mysql
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tideways
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

2. 重启php-fpm 问题是否还在？
在
3. 直接在浏览器中访问 http://test.com/xhgui-branch/external/header.php  （修改为自己的URL）是否报错

**具体报错信息：**
一直显示下面这个，不知道哪边没配置好

看起来你没有做任何配置

你需要收集一些分析数据才能开始使用XHGUI

**Comment by laynefyc** [comment]
直接在浏览器中访问 http://test.com/xhgui-branch/external/header.php （修改为自己的URL）是否报错。 报错信息是什么？
