### ISSUE TITLE
采集不到任何数据

### ISSUE THREAD

**Issue by tonsionw** [laynefyc/xhgui-branch#52]
**一定要读**
在提交BUG之前请查阅README文件，常见的安装与配置问题都有对应解决办法 。再查看历史ISSUE https://github.com/laynefyc/xhgui-branch/issues?utf8=%E2%9C%93&q=is%3Aissue 是否有答案。都解决不了，请认真填写如下信息

**版本信息:**
 - 操作系统: [e.g. CentOS 7]
 - PHP [e.g. PHP7.1.18]
 - 扩展 [e.g. tideway.so v5.0.48]
 - MongodDB 版本 [e.g. MongodDB v3.2.22]

**PHP信息:**
1. 运行php -m 将结果粘贴到当前文本中
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tideways
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

2. 重启php-fpm 问题是否还在？
是
3. 直接在浏览器中访问 http://test.com/xhgui-branch/external/header.php  （修改为自己的URL）是否报错
？不明白这个要求是什么意思。
这个url怎么可能访问的了，肯定是File not found.啊
不管是xhgui的http://xhgui.wtx.com/xhgui-branch/external/header.php
还是我要监控的站http://rrjk.wtx.com/xhgui-branch/external/header.php
**具体报错信息：**

我这里是不管网站怎么运行，都没采集到任何信息。
贴上我的nginx配置
server {
        listen       80;
        server_name  rrjk.wtx.com ;
        root   /vagrant_data/www/jiankang;
	    fastcgi_param PHP_VALUE "auto_prepend_file=/vagrant_data/www/xhgui-branch/external/header.php";
        location / {
            index  index.html index.htm index.php;
            #autoindex  on;
			if (!-e $request_filename) {
   				rewrite  ^(.*)$  /index.php?s=/$1  last;
  				 break;
    		}
        }
	
        location ~ \.php(.*)$ {
            fastcgi_pass   unix:/tmp/php-cgi.sock;
            fastcgi_index  index.php;
            fastcgi_split_path_info  ^((?U).+\.php)(/?.+)$;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO  $fastcgi_path_info;
            fastcgi_param  PATH_TRANSLATED  $document_root$fastcgi_path_info;
            include        fastcgi_params;
        }
}

**Comment by laynefyc** [comment]
/vagrant_data/www/xhgui-branch/external/header.php   在浏览器里面访问到这个文件看是否报错，日志的收集原理就是通过 在请求里 require /vagrant_data/www/xhgui-branch/external/header.php 实现的。所以想办法在浏览器里访问external/header.php文件，能拿到详细错误信息。

**Comment by 727561126** [comment]
解决了吗  我也碰到相同的问题
