### ISSUE TITLE
有些图表不显示

### ISSUE THREAD

**Issue by xujinhui2015** [laynefyc/xhgui-branch#59]
**版本信息:**
 - 操作系统: CentOS 7.1
 - PHP PHP5.6
 - 扩展  tideway.so v4.16
 - MongodDB 版本v3.4.22

**PHP信息:**
1. 运行php -m 将结果粘贴到当前文本中
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
ereg
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mongodb
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tideways
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend Guard Loader
zip
zlib
2. 重启php-fpm 问题是否还在？
还在
3. 直接在浏览器中访问 http://test.com/xhgui-branch/external/header.php  （修改为自己的URL）是否报错
否

**具体报错信息：**
为什么图表没有折线图显示呢？
![Image text](https://s2.ax1x.com/2019/09/01/nphj39.png)

**Comment by mcu-shengwei** [comment]
我也是不显示这个折线图，我同时部署了原版xugui，结果不但折线图不显示，而且执行sql也不显示了

**Comment by laynefyc** [comment]
@xujinhui2015   不是不显示，横坐标默认以天作为区间，你的请求数据都发生在9.1号，所以只能看到一个点

**Comment by laynefyc** [comment]
@mcu-shengwei   显示SQL是我开发的扩展功能，原版确实是没有的。
