### ISSUE TITLE
请求的列表中，偶尔时间排序不对，需要怎么解决

### ISSUE THREAD

**Issue by xujinhui2015** [laynefyc/xhgui-branch#62]
版本信息:

操作系统: CentOS 7.1
PHP PHP5.6
扩展 tideway.so v4.16
MongodDB 版本v3.4.22
PHP信息:

运行php -m 将结果粘贴到当前文本中
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
ereg
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mongodb
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tideways
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend Guard Loader
zip
zlib
重启php-fpm 问题是否还在？
还在
直接在浏览器中访问 http://test.com/xhgui-branch/external/header.php （修改为自己的URL）是否报错
否
具体报错信息：
我点了按时间排序也是一样
![image](https://user-images.githubusercontent.com/16284992/64951834-62ce2980-d8b1-11e9-87be-93f22a9cb506.png)

**Comment by laynefyc** [comment]
按时间排序的请求链接发出来看看

**Comment by xujinhui2015** [comment]
链接： /?direction=desc&sort=time

**Comment by laynefyc** [comment]
https://github.com/laynefyc/xhgui-branch/issues/58    参考这位同学的办法试试
