### ISSUE TITLE
给个建议在IP列上加一个IP地址查看地址的，我觉得挺好用

### ISSUE THREAD

**Issue by xujinhui2015** [laynefyc/xhgui-branch#63]
我用的是https://github.com/itbdw/ip-database 这个库，有时候识别下地址更方便判断这个IP是否异常

![image](https://user-images.githubusercontent.com/16284992/65672686-053d9800-e07c-11e9-9477-ec8258f3958c.png)

![image](https://user-images.githubusercontent.com/16284992/65672938-78dfa500-e07c-11e9-8085-0614b950a4fa.png)

**Comment by laynefyc** [comment]
谢谢建议，这个功能我们内部的项目其实加了的，用的高春辉的ipip免费库。不过IP转换更适合玩家自己扩展，不适合放在主分支中。纯真库有时效性需要定期更新，作为性能分析工具来说IP来源其实没那么重要，这部分功能更适合放在ELK中。

**Comment by xujinhui2015** [comment]
好的，谢谢大佬，从项目首页看到你的博客，想进去学习下的，发现失效了，能修复一下吗？
![image](https://user-images.githubusercontent.com/16284992/65848560-361e1580-e379-11e9-9576-44cd4b6abef0.png)

**Comment by laynefyc** [comment]
https://blog.it2048.cn/   没问题啊。
