### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xioayangguang** [laynefyc/xhgui-branch#64]
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function tideways_enable() in /www/web/xhgui/external/header.php:101

解决见官网https://support.tideways.com/article/183-uncaught-error-call-to-undefined-function-tidewaysenable

可以安装这个扩展
https://github.com/tideways/php-xhprof-extension

**Comment by laynefyc** [comment]
Readme文件和Issues中有描述

**Comment by xioayangguang** [comment]
我照着博客安装的https://blog.it2048.cn/article-tideways-xhgui/
