### ISSUE TITLE
希望可以支持多域名展示和搜索

### ISSUE THREAD

**Issue by yiqiang3344** [laynefyc/xhgui-branch#68]
目前列表的请求地址只有路由没有域名地址。想要监控多个站点时，就不方便使用了。我做了一些自定义，实现了域名的搜索和展示。作者是否允许提交？

**Comment by laynefyc** [comment]
可以提交，域名问题已经有很多人问了，新版本已经加了这个功能 https://github.com/laynefyc/php-monitor
