### ISSUE TITLE
改进求助

### ISSUE THREAD

**Issue by huhufan** [laynefyc/xhgui-branch#72]
**改进求助**

**版本信息:**
 - 操作系统: [MacOS 10.14.5]
 - PHP [PHP7.3.19]
 - 扩展 [tideways_xhprof v5.0.2]
 - MongodDB 版本 [MongodDB v4.2.8]

**具体问题**
 - 我使用的是 [https://github.com/perftools/xhgui/xhgui](url) ，并不是您的改进版本。mysql中sql语句的执行性能分析是否需要自定义，我看db中没有存入sql语句执行的分析数据。如果需要自定义才能实现sql语句的性能分析，我想了解一下相关思路或需要改动的地方。
 -   我看安装指导里需要在nginx的配置文件server中加入这一行，
    `fastcgi_param PHP_VALUE"auto_prepend_file=/Users/markstory/Sites/xhgui/external/header.php";`
   但是加了这一行后，我进行测试发现不是这个server的请求也会进行性能分析，删掉义原来server中的这一行后再重试，发现并不影响使用，所有的请求确实都会进行性能分析。（只修改过nginx的配置文件，其他配置文件没动过，nginx也进行重启和重载了）。

**Comment by laynefyc** [comment]
麻烦读读README。

1. tideways的新版扩展已经更名，并且不支持SQL显示，建议使用支持SQL展示的V4版本 v4.1.6。特定版本才能支持SQL显示；
2. 因为php-fpm进程会重用，虽然server变了但在php-fpm进程没变。
