### ISSUE TITLE
不显示时间

### ISSUE THREAD

**Issue by aylazhang** [laynefyc/xhgui-branch#8]
![image](https://user-images.githubusercontent.com/2088252/31752860-c7e288d8-b4bf-11e7-8beb-e8f95b2f2ba9.png)

请问，可能是什么问题？

**Comment by aylazhang** [comment]
执行时间，ｃｐｕ时间等都没显示。

**Comment by laynefyc** [comment]
操作系统，PHP版本都提供一下

**Comment by wujingfeng** [comment]
我也遇到了  请问应该怎么解决啊   Ubuntu操作系统  PHP7  MongoDB4
![image](https://user-images.githubusercontent.com/22093289/58942413-48fc5100-87b0-11e9-9ffa-b3f244d26109.png)
